# DO NOT CHANGE: [Colored messages file version 3]
# Player accomplishments
:no_skip
:yellow
just have completed a quest.
Congratulations! You advance to level %d.

# Beneficial date effects
You feel that starting your adventure on Creator's Day was a good idea.
A lone star leads you to this remote valley.
You feel well prepared for the coming year.
You feel treated.

# Stat gain
:no_skip
:light green
Your muscles feel stronger.
You suddenly feel stronger!
You feel studious.
Your will seems inflexible.
Your movements are getting swifter.
Your health increases.
You feel very self-confident.
Your looks improve.
You feel more in touch with the world.
Your senses sharpen.
feel good about your %s potential.
feel very good about your %s level.

# Stat loss
:no_skip
:red
You feel as if this was not a good idea!
Your muscles soften.
Thinking seems to get tougher.
You feel soft-hearted.
You are getting shaky.
It seems that you are getting a cold.
You feel reserved.
You are growing a wart.
You are getting out of touch with everything.
You seem to get less perceptive.
You feel weak!
You feel exhausted!
You suddenly age!
You feel a chill... you sense rapidly increasing danger in this place!
You sense that your time is running out in this place and Death's claws are gripping after you!
You sense a foreboding of doom... as if something here is going to kill you very soon!
You lose all sense of hope of getting out of here alive!
You feel the urge to run away from here... as fast as you can!

# Skill gain
:no_skip
:light blue
Your '%s' skill increases by %+d
to %d.
improve in the area of '%s' (from %s to
%s).
improve your skill in the shield group to level %d.
improve your skill in the '%s' weapon group to level %d.
improve your skill with the '%s' weapon category to level %d.
become more efficient in using the '%s' spell (now %+d).

# Equipment damage/destruction
:no_skip
:red
Your {equipped} %s are destroyed!
Your {equipped} %s are damaged!
Your {equipped} %s corrodes!
Your {equipped} %s corrode!
Your {equipped} %s %s damaged.
Your {equipped} %s %s destroyed!
Your {equipped} %s rust%s!
%lld %sof your {equipped} %s %s!
Your {equipped} %s %s!
Your %s are destroyed.
Your %s are damaged.
Your %s corrodes!
Your %s corrode!
It is destroyed.
They are destroyed.
Your weapon breaks!
Your %s %s damaged.
Your %s %s destroyed!
Your %s rust%s!
%lld %sof your %s %s!
Your %s %s!
Your %s is finally damaged beyond repair!
The %s on the floor melts down into a puddle of metal!
The %s %s %s!
The %s %s transformed into a rusty heap!
The %s rust%s!
It is annihilated!
They are annihilated!

# Detrimental date effects
You feel unlucky.
You feel slightly exhausted today.

# Food rotting
:no_skip
:brown
Your equipment seems to become smelly.
Your equipment suddenly seems to weigh less.
Your %s rots away!
Your %s starts to rot!
Your %s slowly rots away!
notice %s %s rotting away.

# Spell effect messages
:no_skip
:cyan
You feel your spirits rise!
You feel your spirits soar!
Your mood darkens.
Your eyes itch.
Your eyesight adjusts to normality once more.
You feel like Atlas himself.
You feel your great strength waning.
Suddenly your extraordinary carrying capacity fails you.
Suddenly everything around you seems to speed up!
Suddenly everything around you seems to slow down.
Suddenly you can't see yourself!
For a moment you were gone... then your eyes adjust.
Suddenly you can see yourself again!

# Special room messages
:no_skip
:white
You hear an eerie wail for a few seconds...
You notice a pale fading ball of light upon entering this room.
It quickly disappears.
A rat scurries between your feet and disappears in a small hole in the ground.
The breeze accompanying you causes some ancient bones on the floor to transform into dust.
You feel a sense of relief.
Upon entering this room you feel a strange magical shock!
This room seems to be particularly unholy!
You hear a strange "*TCHUNK*" in your vicinity.
For a few seconds you see a looming shade before you. It points its hand towards you in a threatening manner! Then it disappears.
A mouth appears on the wall and says: "%s".
Then it disappears.
For a moment a mouth appears on the wall and seems to say something!
The walls have mirrors with many distortions of your image.
You look great in all of them.
You can't stand the sight of your warped self.
All the mirrors shatter!
Images of books and comfortable chairs line the walls.
Suddenly the images fade away!
This room looks like a spa with a mud bath. You are hit in the face by a glob of hot mud!
Suddenly everything disappears!
This seems to be some kind of ancient treasure vault.
Your steps suddenly sound hollow.
You get the odd feeling that something is wrong with your perception of this room, but can't seem to tell what it is from just looking around.
Something is oddly wrong with the location you just entered although you aren't yet sure what it might be.
There seems to be a shifting breeze in this room.
This seems to be a very dull room.
The air in this room seems to be magically charged.
This room smells of herbs and antiseptics.
The walls of this room are made of many small stones of uniform height; they almost look like shelves of books.
The skulls of many creatures are embedded in the walls. It's almost like being in the grave with them.
Strange lights flicker in this room.
The floor of this room seems to be very sticky.
This room seems to be incredibly ancient.
You sense the presence of some supernatural entity of benevolent nature.
You sense the presence of some supernatural entity of malevolent disposition.
The air of this room is filled with a very rich flavor.
This room seems to be tainted by evil.
The aura of this room seems to be devoid of all life!
The walls and the ceiling of this room are sewn with cracks.
This room is very humid.
The atmosphere of this room makes your skin tingle!
The air in this room is stale in a highly unnatural way.
This room seems to be filled with a deadly and chilling silence.
All sounds are muffled.
This room seems to vibrate with life.
Insects are crawling everywhere, strange mushrooms cover the walls and moss is growing at the ceiling.
The walls of this room seem to be made from pure obsidian.
The floor of this room is covered with puddles of ancient dried blood.
The walls of this room are covered with ancient runes.
The walls of this room are scarred by the signs of many fights. Most parts of the room are heavily damaged.
The air of this room is filled with the smell of carrots.
The walls of this room are covered with leering visages of demons of all kind!
The air of this room refreshes you and sharpens your spirits!
Hundreds of tiny insects are crawling beneath your feet and the whole ground seems to be covered with tiny white eggs!
You hear a crunching sound beneath your feet.

# Unnecessary messages
:suppress
Select the companion you want to issue an order to.
Select the slave to command.
#(easily cutting through %s armor with the %s)
#You lust for blood!
#The %s returns!
#You manage to catch it.
#You fail to catch it.
